export const DAMAGE_NUMBER_MAX_ACTIVE = 12;
export const DAMAGE_NUMBER_MAX_ACTIVE_PRIORITY = 18;
export const DAMAGE_NUMBER_NORMAL_LIFETIME_MS = 420;
export const DAMAGE_NUMBER_ELITE_LIFETIME_MS = 520;
export const DAMAGE_NUMBER_BOSS_LIFETIME_MS = 620;
export const DAMAGE_NUMBER_NORMAL_RISE_PX = 16;
export const DAMAGE_NUMBER_ELITE_RISE_PX = 20;
export const DAMAGE_NUMBER_BOSS_RISE_PX = 24;
