export const OFFSCREEN_INDICATOR_INSET = 18;
export const OFFSCREEN_INDICATOR_SIZE = 9;
export const OFFSCREEN_INDICATOR_MAX = 12;
export const OFFSCREEN_PRIORITY_BONUS_ELITE = 10000;
export const OFFSCREEN_PRIORITY_BONUS_BOSS = 20000;
